on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n MCtest22 -g MCtest22a714-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n MCtest22 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n MCtest22 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n MCtest22 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: mctest22.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/bungeecord" -f  "bungeecord/Dockerfile" -t mctest22.azurecr.io/mctest:${{ github.sha }} --label dockerfile-path=bungeecord/Dockerfile
        docker push mctest22.azurecr.io/mctest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_mctest_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mc-test9ff2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mc-test9ff2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mc-test9ff2
        container-registry-url: mctest22.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: mctestdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mc-test9ff2
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          mctest22.azurecr.io/mctest:${{ github.sha }}
        imagepullsecrets: |
          mctestdockerauth   
